config/routes.rb
Rails.application.routes.draw do
  root to: 'discover_home#home'
  devise_for :users, path: "", path_names: {sign_in: "login", sign_out: "logout"}
  get "/preview", to: "preview#index", as: "preview"
  
  resources :users do
    resources :images
    resources :galleries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/users/:id/unfollow", to: "users#unfollow", as: "unfollow_user"
  get "/users/:id/follow", to: "users#follow", as: "follow_user"

  get "/users/:id/home", to: "discover_home#home", as: "discover_home_home"
  get "/users/:id/discover", to: "discover_home#discover", as: "discover_home_discover"
  
  # get "/public", to: "discover_home#public", as: "discover_home_public"
  
  get "/images/:id/buy", to: "images#buy", as: "images_buy"  
  
  get "/galleries/:id/buy", to: "galleries#buy", as: "galleries_buy"  
  delete "/galleries/:id/remove", to: "galleries#remove_image", as: "remove_image"  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
    
    has_many :images, dependent: :destroy
    # has_many :gallery_images,  through: :galleries
    has_many :galleries, dependent: :destroy

     # Will return an array of follows for the given user instance
    has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

    # Will return an array of users who follow the user instance
    has_many :followers, through: :received_follows, source: :follower
  
    #####################
  
    # returns an array of follows a user gave to someone else
    has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
  
    # returns an array of other users who the user has followed
    has_many :followings, through: :given_follows, source: :followed_user

    mount_uploader :profile_picture, ProfilePictureUploader

  private
    def set_user_status
      self.status = 'pending'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy follow unfollow ]
  before_action :authenticate_user! 

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    # if current_user.id != params[:id].to_i
    #   redirect_to "/users/#{current_user.id}"
    # end
    @user = User.find(params[:id].to_i)
    @is_following = false
    current_user.followings.each do |following|
      if following.id == @user.id
        @is_following = true
        break
      end
    end
    @images = @user.images.where(bought: false).order(created_at: :desc)
    @bought_images = @user.images.where(bought: true).order(created_at: :desc)
    @bought_galleries = @user.galleries.where(bought: true).order(updated_at: :desc)
    @galleries = @user.galleries.where(bought: false).order(created_at: :desc)
  end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # def update_status
  #   if authenticate_if_admin!
  #     if single_trader.update(status: 'approved')
  #       TraderMailer.with(trader: single_trader).approved_account_receipt.deliver_later
  #       render json: { status: 'approved', message: 'Trader status changed to approved' }, status: 200
  #     else
  #       render json: { error: 'Trader status change failed' }, status: 422
  #     end
  #   else
  #     render json: { error: 'You are not authorized to view this page.' }, status: 401
  #   end
  # end

  # DELETE /users/1 or /users/1.json
  def destroy
    current_user.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def follow 
    Follow.create({
      :follower_id => current_user.id,
      :followed_user_id => @user.id 
    })
    redirect_to "/users/#{@user.id}" #needs to remove this 
  end

  def unfollow
    Follow.where(follower_id: current_user.id, followed_user_id: @user.id).destroy_all
    redirect_to "/users/#{@user.id}"
  end
  private

    def get_user
      @user = User.find(params[:user_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :name, :email, :profile_picture, :balance, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div>
    
    <%= form_tag(users_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search])%>
        <%= submit_tag ("search")%>
    <% end %>

    <% if params[:search] %>
        <% @users.each do |user| %>
            <ul>
                <li><%= link_to user.username, user_path(user)%></li>
            </ul>
        <% end %>
    <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
            <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
  <% end %>
    <div  class='h-screen grid grid-cols-5'>
        <div class='h-full text-xl flex text-base flex-col col-start-2 col-end-5 items-center border-x-2 border-black justify-center '>
            <div class='w-4/6'>
                <div class="w-full my-4">
                    <%= f.label :username %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :username, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :name %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :name, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :email %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :email, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :bio %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_area :bio, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :balance %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.number_field :balance, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :profile_picture %><br />
                    <div class='mt-6 border-black'>
                        <%= f.file_field :profile_picture, :style => 'width: 100%' %>
                    </div>
                </div>
                
                <div class="w-full mt-8 flex justify-center">
                    <button class='bg-black text-white py-2 px-4 '><%= f.submit 'Update'%></button>
                </div>
                
                <button class='btns text-base flex justify-center py-2 text-black bg-grey px-2 mt-6'>
                    <%= link_to 'Delete my account', current_user, method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %>
                </button>
            </div>
        </div>
    </div>
<% end %>

app/views/users/search_results.html.erb
<li>search</li>

<%=render @users %>

app/views/users/show.html.erb
<div class='grid grid-cols-5 min-h-[40%]'>
  <div class='h-full my-profile flex flex-col justify-evenly items-center col-start-3 mt-2'>
    <div class='profile mt-2 flex flex-col w-full'>
      <% if @user.id == current_user.id %>
        <button class='absolute text-grey text-base self-end mr-10'>
          <%= link_to(edit_user_path(@user)) do %>
            <i class="fa fa-pen"></i>
          <% end %>
        </button>
      <% end %>
      <% if @user.profile_picture? %>
        <%= image_tag @user.profile_picture.to_s, :class =>'mx-4 rounded-full self-center', :style => 'object-fit:cover; width:80px; height:80px' %>   
      <% else %>
        <%= image_tag 'user.jpg', :class =>'mx-4 rounded-full self-center', :style => 'object-fit:cover; width:80px; height:80px' %>
      <% end %>
    </div>
    <div class='w-11/12 h-80% flex justify-around items-center mt-2'>
      <div class='flex flex-nowrap text-lg self-center'>
        <span class='mx-2'><%= @user.name %></span>
        <% if @user.id != current_user.id %>
          <% if @is_following %>
            <button class='btns text-base flex justify-center py-2 text-white bg-black px-2 -mt-2'>
              <%= link_to 'unfollow', unfollow_user_path(@user) %>
            </button>   
          <% else %>
            <button class='btns text-base flex justify-center py-2 text-white bg-black px-2 -mt-2'>
              <%= link_to 'follow', follow_user_path(@user) %>
            </button>
          <%end%>
        <% end %>
      </div>
    </div>
    <p class='text-grey mt-2'>
      <%= @user.username %>
    </p>
    <p class='text-grey mt-2 text-center overflow-y-auto no-scrollbar text-sm  max-h-28'>
      <%= @user.bio %>
    </p>
  </div>
</div>

<ul class="nav nav-tabs flex flex-col md:flex-row flex-wrap list-none border-b-0 pl-0 mt-5" id="tabs-tabFill"
  role="tablist">
  <li class="nav-item flex-auto text-center border-y-2 border-black" role="presentation">
    <a href="#tabs-homeFill" class="
      <%# nav-link %>
      w-full
      block
      <%# font-medium %>
      <%# text-xs %>
      text-base
      leading-tight
      <%# uppercase %>
      border-x-0 border-t-0 border-b-2 border-transparent
      px-6
      py-3
      my-2
      hover:text-grey
      <%# hover:border-transparent hover:bg-gray-100 %>
      focus:border-transparent
      active
    " id="tabs-home-tabFill" data-bs-toggle="pill" data-bs-target="#tabs-homeFill" role="tab"
      aria-controls="tabs-homeFill" aria-selected="true">Photo</a>
  </li>
  <li class="nav-item flex-auto text-center border-y-2 border-black" role="presentation">
    <a href="#tabs-profileFill" class="
      <%# nav-link %>
      w-full
      block
      <%# font-medium %>
      <%# text-xs %>
      text-base
      leading-tight
      <%# uppercase %>
      border-x-0 border-t-0 border-b-2 border-transparent
      px-6
      py-3
      my-2
      hover:text-grey
      <%# hover:border-transparent hover:bg-gray-100 %>
      focus:border-transparent
    " id="tabs-profile-tabFill" data-bs-toggle="pill" data-bs-target="#tabs-profileFill" role="tab"
      aria-controls="tabs-profileFill" aria-selected="false">Gallery</a>
  </li>
  <li class="nav-item flex-auto text-center border-y-2 border-black" role="presentation">
    <a href="#tabs-messagesFill" class="
      <%# nav-link %>
      w-full
      block
      <%# font-medium %>
      <%# text-xs %>
      text-base
      leading-tight
      <%# uppercase %>
      border-x-0 border-t-0 border-b-2 border-transparent
      px-6
      py-3
      my-2
      hover:text-grey
      <%# hover:border-transparent hover:bg-gray-100 %>
      focus:border-transparent
    " id="tabs-messages-tabFill" data-bs-toggle="pill" data-bs-target="#tabs-messagesFill" role="tab"
      aria-controls="tabs-messagesFill" aria-selected="false">Collection</a>
  </li>
</ul>
<div class="tab-content" id="tabs-tabContentFill">
  <div class="tab-pane fade show active" id="tabs-homeFill" role="tabpanel" aria-labelledby="tabs-home-tabFill">
    <% if @user.id == current_user.id %>
      <button class='mt-2 h-fit w-fit py-2.5 px-4 text-white bg-black'><%= link_to 'Upload a photo', new_user_image_path(@user) %></button>  
    <% end %>
    <%= render 'images/index' %>
  </div>
  <div class="tab-pane fade" id="tabs-profileFill" role="tabpanel" aria-labelledby="tabs-profile-tabFill">
    <% if @user.id == current_user.id %>
      <button class='mt-2 h-fit w-fit py-2.5 px-4 text-white bg-black'><%= link_to 'Create a gallery', new_user_gallery_path(@user) %></button>  
    <% end %>
    <%= render 'galleries/index' %>
  </div>
  <div class="tab-pane fade" id="tabs-messagesFill" role="tabpanel" aria-labelledby="tabs-profile-tabFill">
    <%= render 'images/collection' %>
  </div>
</div>