config/routes.rb
Rails.application.routes.draw do
  root to: 'discover_home#home'
  devise_for :users, path: "", path_names: {sign_in: "login", sign_out: "logout"}
  get "/preview", to: "preview#index", as: "preview"
  
  resources :users do
    resources :images
    resources :galleries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/users/:id/unfollow", to: "users#unfollow", as: "unfollow_user"
  get "/users/:id/follow", to: "users#follow", as: "follow_user"

  get "/users/:id/home", to: "discover_home#home", as: "discover_home_home"
  get "/users/:id/discover", to: "discover_home#discover", as: "discover_home_discover"
  
  # get "/public", to: "discover_home#public", as: "discover_home_public"
  
  get "/images/:id/buy", to: "images#buy", as: "images_buy"  
  
  get "/galleries/:id/buy", to: "galleries#buy", as: "galleries_buy"  
  delete "/galleries/:id/remove", to: "galleries#remove_image", as: "remove_image"  
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    validates :user_id, presence: true
    validates :title, presence: true, length: { maximum: 40 }

    has_many :images 
    has_many :gallery_images
    has_many :images, through: :gallery_images

    belongs_to :user
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[ show edit update destroy buy ]
  before_action :get_user

  # GET /galleries or /galleries.json
  def index
    @galleries = @user.galleries.order(created_at: :desc)
  end

  # GET /galleries/1 or /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
    @galleries = @user.galleries.where(bought: false).order(created_at: :desc)
    @bought_galleries = @user.galleries.where(bought: true).order(created_at: :desc)
  end

  # GET /galleries/new
  def new
    @gallery = @user.galleries.build
    @images = @user.images.order(created_at: :desc)
  end
  
  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
    @image_ids = @gallery.gallery_images.pluck(:image_id)
    @images = @user.images.order(created_at: :desc)
  end

  # POST /galleries or /galleries.json
  def create
    gallery_params[:user_id] = current_user.id
    @gallery = @user.galleries.build(gallery_params)

    respond_to do |format|
      if params["gallery"]["image_ids"] && @gallery.save     
        params["gallery"]["image_ids"].each do |image_id|
          GalleryImage.create({
            :gallery_id => @gallery.id,
            :image_id => image_id
          })
        end

        format.html { redirect_to user_gallery_path(@user.id, @gallery), notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    gallery_params[:user_id] = current_user.id

    respond_to do |format|
      if params["gallery"]["image_ids"] && @gallery.update(gallery_params)
        @gallery.gallery_images.delete_all
        params["gallery"]["image_ids"].each do |image_id|
          GalleryImage.create({
            :gallery_id => @gallery.id,
            :image_id => image_id
          })
        end
        format.html { redirect_to user_gallery_path(@user.id, @gallery), notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buy
    if current_user.balance >= @gallery.gallery_price
      current_user.balance = current_user.balance - @gallery.gallery_price
      current_user.save

      owner = User.find(@gallery.user_id)
      owner.balance = owner.balance + @gallery.gallery_price
      owner.save

      @gallery.user_id = current_user.id
      @gallery.gallery_price = 0
      @gallery.bought = true
      @gallery.save

      redirect_to user_path(current_user)
    else
      respond_to do |format|
        format.html { render 'images/insufficient_funds', status: :unprocessable_entity  }
      end
    end
  end

  private
    def get_user
      @user = User.find(current_user.id)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.require(:gallery).permit(:title, :caption, :gallery_price)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_index.html.erb
<div class='w-full grid grid-cols-3 mx-5 mb-5 gap-5 flex justify-center items-start mt-20'>
  <% if @galleries %>
    <% @galleries.each do |gallery|%>
      <div class= 'flex flex-col w-96 h-auto'>
        <% if gallery.images %>
          <%= link_to image_tag(gallery.images.first.img.to_s), user_gallery_path(current_user, gallery) %>
          <div class='w-full grid grid-cols-2 mt-4 flex'>
            <span class='mr-4 col-start-1 flex justify-start font-semibold pl-2'><%= gallery.title %></span>
            <% if gallery.gallery_price != nil and gallery.gallery_price > 0 %>
              <span class='col-start-2 flex justify-end pr-2'><%= gallery.gallery_price %> PHP</span>
            <% end %>
          </div>
          <div class='w-full max-h-28 flex justify-start pl-2 overflow-y-auto no-scrollbar text-sm'>
            <span class='col-start-1'><%= gallery.caption %></span>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/galleries/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @gallery.caption %>
</p>

<p>
  <strong>Price:</strong>
  <%= @gallery.gallery_price %>
</p>

<p>
  <strong>Images</strong>
  <%= @gallery.images %>
</p>

<%= link_to 'Edit', edit_user_gallery_path(@user, @gallery) %> 
<%= link_to 'Back', user_galleries_path(@user) %>

app/views/galleries/edit.html.erb
<%= form_with model: [@user, @gallery],  local: true do |f| %>
    <div  class='h-screen grid grid-cols-5'>
        <div class='h-full text-xl flex flex-col col-start-2 col-end-5 items-center border-x-2 border-black justify-center '>
            <div class='w-4/6 h-5/6'>
                <div class="w-full my-4">
                    <%= f.label :title %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :title, :style => 'width: 100%' %>
                    </div>
                </div>
                <div class="w-full my-4">
                    <%= f.label :caption %><br />
                    <div class='border-b-2 border-black w-full'>
                        <%= f.text_area :caption, :style => 'width: 100%' %>
                    </div>
                </div>           
                <div class="w-full my-4">
                    <%= f.label :gallery_price %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.number_field :gallery_price, :style => 'width: 100%' %>
                    </div>
                </div>
                <div class='flex grid grid-cols-3'>
                    <% @images.each do |image|%>
                        <div class= 'flex flex-col max-w-sm h-auto'>
                            <div class='flex h-full'>
                                <% if @image_ids.include? image.id %>
                                  <%= check_box_tag "gallery[image_ids][]", image.id, true %>
                                <% else %>
                                  <%= check_box_tag "gallery[image_ids][]", image.id %>
                                <% end %>
                              <%= image_tag(image.img.to_s) %>
                            </div>
                        </div>
                    <% end %>
                </div>
                <div class="w-full mt-8 flex justify-center">
                    <button class='bg-black text-white py-2 px-4 '><%= f.submit 'Save'%></button>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/galleries/new.html.erb
<%= form_with model: [@user, @gallery],  local: true do |f| %>
    <div  class='h-screen grid grid-cols-5'>
        <div class='h-full text-xl flex flex-col col-start-2 col-end-5 items-center border-x-2 border-black justify-center '>
            <div class='w-4/6 h-5/6'>
                <div class="w-full my-4">
                    <%= f.label :title %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :title, :style => 'width: 100%' %>
                    </div>
                </div>
                <div class="w-full my-4">
                    <%= f.label :caption %><br />
                    <div class='border-b-2 border-black w-full'>
                        <%= f.text_area :caption, :style => 'width: 100%' %>
                    </div>
                </div>           
                <div class="w-full my-4">
                    <%= f.label :gallery_price %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.number_field :gallery_price, :style => 'width: 100%' %>
                    </div>
                </div>
                <div class='flex grid grid-cols-3'>
                    <% @images.each do |image| %>
                        <div class= 'flex flex-col max-w-sm h-auto'>
                            <div class='flex h-full'>
                              <%= check_box_tag "gallery[image_ids][]", image.id %>
                              <%= image_tag(image.img.to_s) %>
                            </div>
                        </div>
                    <% end %>
                </div>
                <div class="w-full mt-8 flex justify-center">
                    <button class='bg-black text-white py-2 px-4 '><%= f.submit 'Create a gallery'%></button>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/galleries/show.html.erb
<div class= 'h-screen w-screen flex flex-col items-center mt-20'>
  <div class='w-11/12 flex grid grid-cols-2 mb-10'>
  <span class='font-bold text-2xl'><%= @gallery.title %></span>
  <% if @gallery.gallery_price != nil and @gallery.gallery_price > 0 %>
    <span class='flex justify-end font-bold text-2xl justify-end'>PHP <%= @gallery.gallery_price %></span>
  <% end %>
  </div>    
  <span class='text-base w-11/12'><%= safe_join(@gallery.caption.split("\n"),tag(:br)) %></span>
  
  <div class='w-11/12 grid grid-cols-3 mx-5 mb-5 gap-5 flex justify-center'>
      <% @gallery.images.each do |image| %>
          <div class='mt-8 w-96 h-auto'>
            <%= image_tag image.img.to_s, :style => 'object-fit:contain; max-width:400px; max-height:400px' %>
          </div>
      <% end %>
  </div>
    <div class='btns mt-8 mb-4'>
      <% if @gallery.user_id == current_user.id %>
        <div>
          <span class='mx-2'><%= link_to 'Delete', user_gallery_path(current_user, @gallery), method: :delete, data: { confirm: 'Are you sure?' } %></span> |
          <span class='mx-2'><%= link_to 'Edit', edit_user_gallery_path(current_user, @gallery) %></span>
        </div>
      <% else %>
        <button class='border-2 px-4 py-2 bg-black text-white mt-8'><%= link_to 'BUY', galleries_buy_path(@gallery)%></button>
      <% end %>
    </div>
</div>