config/routes.rb
Rails.application.routes.draw do
  root to: 'discover_home#home'
  devise_for :users, path: "", path_names: {sign_in: "login", sign_out: "logout"}
  get "/preview", to: "preview#index", as: "preview"
  
  resources :users do
    resources :images
    resources :galleries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/users/:id/unfollow", to: "users#unfollow", as: "unfollow_user"
  get "/users/:id/follow", to: "users#follow", as: "follow_user"

  get "/users/:id/home", to: "discover_home#home", as: "discover_home_home"
  get "/users/:id/discover", to: "discover_home#discover", as: "discover_home_discover"
  
  # get "/public", to: "discover_home#public", as: "discover_home_public"
  
  get "/images/:id/buy", to: "images#buy", as: "images_buy"  
  
  get "/galleries/:id/buy", to: "galleries#buy", as: "galleries_buy"  
  delete "/galleries/:id/remove", to: "galleries#remove_image", as: "remove_image"  
end

app/controllers/discover_home_controller.rb
class DiscoverHomeController < ApplicationController
  before_action :authenticate_user!, except: %i[public]
  before_action :get_user, except: %i[public]

  def home
    @user_ids = current_user.followings.pluck(:id)
    @user_ids.push(current_user.id)
    @images = Image.where(user_id: @user_ids, bought: false).or(Image.where('user_id IN (?) AND price != 0', @user_ids)).order(updated_at: :desc).all
    @suggested_users = User.where.not(id: @user_ids).limit(5)
  end

  def discover
    @images = Image.where(bought: false).or(Image.where('price != 0')).order(created_at: :desc).all
  end

  def public
    # @images = Image.all
    @images = Image.where(bought: false).or(Image.where('price != 0')).order(updated_at: :desc).all
  end
  
  private
    def get_user
      @user = User.find(current_user.id)
    end
end

app/views/discover_home/_public.html.erb
<% if @images.count != 0 %>
  <div class='grid grid-cols-6 grid-rows-3 grid-flow-row-dense'>    
    <div class="min-h-fit flex items-center col-start-2 col-end-6 row-start-1 row-end-3">
      <ul>
        <% @images.each do |image| %>
          <div class='my-4 mt-5 p-5 border-2 pb-4 border-black'>
            <div class='flex items-center mb-4 text-lg'>
              <li><%= image_tag image.user.profile_picture.to_s, :class =>'mx-4 rounded-full bg-green-400', :style => 'object-fit:cover; width:30px; height:30px'%></li>
              <li>
                <%= link_to user_path(image.user.id) do %>
                  <%= image.user.username %>
                <% end %>
              </li>
            </div>
            <div class='flex grid grid-cols-2 mb-4 w-full'>
              <li class='col-start-1 flex mx-4 justify-start'><%= image.title %></li>
              <li class='col-start-2 flex mx-4 justify-end'>
                <%# <% if image.price != nil and image.price > 0 %>
                  <%# <span class= 'p-2 bg-black text-white'>On Market</span> %>
                <%# <% end %>
              </li>
            </div>
            <%# <li class='mx-4'><%= link_to image_tag(image.img.to_s), user_image_path(@user, image), :style => 'height:10px' %></li> %>
            <li class='mt-4 mx-4 max-h-28 overflow-y-auto no-scrollbar'><%= image.caption %></li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <span class='h-full w-full flex justify-center items-center text-2xl'> no content to display </span>
<% end %>

app/views/discover_home/discover.html.erb
<% if @images.count != 0 %>
  <div class='w-full flex justify-center'>
    <div class='w-5/6 grid grid-cols-3 mx-5 gap-5 flex justify-start items-start'>
      <% @images.each do |image|%>
        <div class= 'flex flex-col min-h-max h-fit items-start justify-center w-96 min-h-max mt-5 p-5 border-2 pb-4 border-black'>
          <div class='flex items-center mb-4 text-lg'>
            <% if image.user.profile_picture? %>
              <%= image_tag image.user.profile_picture.to_s, :class =>'mr-4 rounded-full bg-green-400', :style => 'object-fit:cover; width:30px; height:30px'%>
            <% else %>
              <%= image_tag 'user.jpg', :class =>'mr-4 rounded-full self-center', :style => 'object-fit:cover; width:30px; height:30px' %>
            <% end %>  
            <div>
              <%= link_to user_path(image.user.id) do %>
                <%= image.user.username %>
              <% end %>
              <% if !(current_user.followings.include?(image.user)) && image.user_id != current_user.id %>
                <button class= 'p-1 mx-2 border text-xs border-grey text-black'><%= link_to 'Follow', follow_user_path(image.user) %></button>
              <% end %>
            </div>
          </div>
          <div class='flex grid grid-cols-2 mb-4 w-full min-h-max h-9'>
            <li class='col-start-1 flex justify-start'><%= image.title %></li>
            <li class='col-start-2 flex justify-end h-fit text-xs'>
              <% if image.price != nil and image.price > 0 %>
                <span class= 'p-2 bg-black text-white'>On Market</span>
              <% end %>
            </li>
          </div>
          <div class='h-fit w-full flex items-center justify-center'>
            <%= link_to(user_image_path(@user, image)) do %>
              <span class=''><%= image_tag image.img.to_s, :style => 'object-fit:cover; max-width:auto; height:300px' %></span>
            <% end %>
          </div>
          <div class='w-full mt-4 h-28 flex justify-start overflow-y-auto no-scrollbar text-sm'>
            <span><%= image.caption %></span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <span class='h-full w-full flex justify-center items-center text-2xl'> no content to display </span>
<% end %>

app/views/discover_home/home.html.erb
<% if @images != nil && @images.count > 0 %>
  <div class='grid grid-cols-6'>    
    <div class="min-h-fit flex flex-col items-center col-start-2 col-end-5 ">
      <ul class='w-4/5'>
        <% @images.each do |image| %>
          <div class='my-4 mt-5 p-5 border-2 pb-4 border-black'>
            <div class='flex items-center mb-4 text-lg'>
              <% if image.user.profile_picture? %>
                <li><%= image_tag image.user.profile_picture.to_s, :class =>'mx-4 rounded-full bg-green-400', :style => 'object-fit:cover; width:30px; height:30px'%></li>
              <% else %>
                <%= image_tag 'user.jpg', :class =>'mx-4 rounded-full self-center', :style => 'object-fit:cover; width:30px; height:30px' %>
              <% end %>            
              <li>
                <%= link_to user_path(image.user.id) do %>
                  <%= image.user.username %>
                <% end %>
                <% if !@user_ids %>
                  <button class= 'p-1 mx-2 border text-xs border-black text-black'><%= link_to 'Follow', follow_user_path(image.user) %></button>
                <% end %>
              </li>
            </div>
            <div class='flex grid grid-cols-2 mb-4 w-full'>
              <li class='col-start-1 flex mx-4 justify-start'><%= image.title %></li>
              <li class='col-start-2 flex mx-4 justify-end'>
                <% if image.price != nil and image.price > 0 %>
                  <span class= 'p-2 bg-black text-white'>On Market</span>
                <% end %>
              </li>
            </div>
            <li class='mx-4'><%= link_to image_tag(image.img.to_s), user_image_path(@user, image), :style => 'height:10px' %></li>
            <li class='mt-4 mx-4 max-h-28 overflow-y-auto no-scrollbar'><%= image.caption %></li>
          </div>
        <% end %>
      </ul>
    </div>
    <div class='user-profile relative col-start-5 mt-5'>
      <div class='user-profile max-h-fit w-1/6 fixed col-start-5 border-2 border-black'>
        <div class='flex items-center mt-5'>
          <% if @user.profile_picture? %>
            <%= image_tag @user.profile_picture.to_s, :class =>'mx-4 rounded-full', :style => 'object-fit:cover; width:50px; height:50px' %>  
          <% else %>
            <%= image_tag 'user.jpg', :class =>'mx-4 rounded-full self-center', :style => 'object-fit:cover; width:50px; height:50px' %>
          <% end %>
          <div class='flex flex-col justify-center'>
            <span class='text-xs '><%= @user.name %></span>
            <span class='text-xs '><%= @user.username %></span>
          </div> 
        </div>
        <span class='text-xs ml-20 my-4 flex-wrap'>balance: PHP <%= @user.balance %></span>

        <% if @suggested_users %>
          <div class='flex w-full flex-col items-center my-5 text-grey text-xs'>
            <span class=' w-full py-1 ml-4 flex justify-start'>
              Users you can follow
            </span>
            <div class='w-full mt-2'>
              <% @suggested_users.each do |user| %>
                <div class='suggested-users flex items-center py-1'>
                  <% if user.profile_picture? %>
                    <%= image_tag user.profile_picture.to_s, :class =>' mx-4 rounded-full bg-green-400', :style => 'object-fit:cover; width:30px; height:30px' %>
                  <% else %>
                    <%= image_tag 'user.jpg', :class =>'mx-4 rounded-full self-center', :style => 'object-fit:cover; width:30px; height:30px' %>
                  <% end %>
                  <span class='justify-center'><%= link_to user.username, user_path(user) %></span>
                  <span class= 'w-full mr-4 text-xs text-black flex justify-end'>
                    <%= link_to 'Follow', follow_user_path(user) %>
                  </span>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <span class='h-full w-full flex justify-center items-center text-2xl'> no content to display </span>
<% end %>