config/routes.rb
Rails.application.routes.draw do
  root to: 'discover_home#home'
  devise_for :users, path: "", path_names: {sign_in: "login", sign_out: "logout"}
  get "/preview", to: "preview#index", as: "preview"
  
  resources :users do
    resources :images
    resources :galleries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/users/:id/unfollow", to: "users#unfollow", as: "unfollow_user"
  get "/users/:id/follow", to: "users#follow", as: "follow_user"

  get "/users/:id/home", to: "discover_home#home", as: "discover_home_home"
  get "/users/:id/discover", to: "discover_home#discover", as: "discover_home_discover"
  
  # get "/public", to: "discover_home#public", as: "discover_home_public"
  
  get "/images/:id/buy", to: "images#buy", as: "images_buy"  
  
  get "/galleries/:id/buy", to: "galleries#buy", as: "galleries_buy"  
  delete "/galleries/:id/remove", to: "galleries#remove_image", as: "remove_image"  
end

app/models/image.rb
class Image < ApplicationRecord
    validates :user_id, presence: true
    validates :title, length: { maximum: 40 }

    belongs_to :user

    has_many :galleries
    has_many :gallery_images, through: :galleries

    mount_uploader :img, ImgUploader

    def myImage
        ActionController::Base.helpers.image_tag("#{image.url(:thumb)}")
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy buy ]
  before_action :get_user, except: %i[ buy ]

  # GET /images or /images.json
  def index
    @images = @user.images.order(created_at: :desc)
  end

  # GET /images/1 or /images/1.json
  def show
    @image = Image.find(params[:id])
    @images = @user.images.where(bought: false).order(created_at: :desc)
    @bought_images = @user.images.where(bought: true).order(created_at: :desc)
  end

  def edit
    @images = Image.find(params[:id])
  end
  
  # GET /images/new
  def new
    @image = Image.new
  end

  # POST /images or /images.json
  def create
    @image = @user.images.build(image_params) 

    respond_to do |format|
      if @image.save
        format.html { redirect_to user_image_path(@user.id, @image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: user_image_path(@user.id, @image.id) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to user_image_path(@user.id, @image), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: user_image_path(@user.id, @image.id) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buy
    if current_user.balance >= @image.price
      current_user.balance = current_user.balance - @image.price
      current_user.save

      owner = User.find(@image.user_id)
      owner.balance = owner.balance + @image.price
      owner.save

      @image.user_id = current_user.id
      @image.bought = true
      @image.price = 0
      @image.save

      redirect_to user_path(current_user)
    else
      respond_to do |format|
        format.html { render 'images/insufficient_funds', status: :unprocessable_entity  }
      end
    end
  end

  private
    def get_user
      @user = User.find(params[:user_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:title, :caption, :img, :price)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_collection.html.erb
<% if @bought_images != nil %>
  <button class='mt-2 h-fit w-fit py-2.5 px-4 text-white bg-black'>Photos</button>  
<% end %>
<div class='w-full grid grid-cols-3 mx-5 gap-5 mb-5  flex justify-center items-start mt-20'>
  <% @bought_images.each do |image| %>
    <div class= 'flex flex-col items-center justify-center w-96 h-auto'>
      <%= link_to image_tag(image.img.to_s), user_image_path(@user, image)%>
      <div class='w-full grid grid-cols-2 mt-4 flex'>
        <span class='mr-4 col-start-1 flex justify-start font-semibold pl-2'><%= image.title %></span>
        <% if image.price %>
          <span class='col-start-2 flex justify-end pr-2'><%= image.price %> PHP</span>
        <% else %>
          <span class='col-start-2 flex justify-end pr-2'>not for sale</span>
        <% end %>
      </div>
      <div class='w-full max-h-28 flex justify-start pl-2 no-scrollbar overflow-y-auto text-sm'>
        <span class='col-start-1'><%= image.caption %></span>
      </div>
    </div>
  <% end %>
</div>
<% if @bought_images.count > 0 %>
  <button class='mt-2 h-fit w-fit py-2.5 px-4 text-white bg-black'>Galleries</button>  
<% end %>

<div class='w-full grid grid-cols-3 mx-5 gap-5 mb-5  flex justify-center items-start mt-20'>
  <% @bought_galleries.each do |gallery| %>
    <div class= 'flex flex-col items-center justify-center w-96 h-auto'>
      <%= link_to image_tag(gallery.images.first.img.to_s), user_gallery_path(current_user, gallery) %>
      <div class='w-full grid grid-cols-2 mt-4 flex'>
        <span class='mr-4 col-start-1 flex justify-start font-semibold pl-2'><%= gallery.title %></span>
        <% if gallery.gallery_price != nil and gallery.gallery_price > 0 %>
          <span class='col-start-2 flex justify-end pr-2'><%= gallery.gallery_price %> PHP</span>
        <% else %>
          <span class='col-start-2 flex justify-end pr-2'>not for sale</span>
        <% end %>
      </div>
      <div class='w-full max-h-28 flex justify-start pl-2 no-scrollbar overflow-y-auto text-sm'>
        <span class='col-start-1'><%= gallery.caption %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/images/_index.html.erb
<div class='w-full grid grid-cols-3 mx-5 mb-5 gap-5 flex justify-center items-start mt-20'>
  <% @images.each do |image|%>
    <div class= 'flex flex-col items-center justify-center w-96 h-auto'>
      <%= link_to image_tag(image.img.to_s), user_image_path(@user, image)%>
      <div class='w-full grid grid-cols-2 mt-4 flex'>
        <span class='mr-4 col-start-1 flex justify-start font-semibold pl-2'><%= image.title %></span>
        <% if image.price != nil and image.price > 0 %>
          <span class='col-start-2 flex font-semibold  justify-end pr-2'><%= image.price %> PHP</span>
        <% end %>
      </div>
      <div class='w-full max-h-28 flex justify-start pl-2 overflow-y-auto no-scrollbar text-sm'>
        <span class='col-start-1'><%= image.caption %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/images/edit.html.erb
<%= form_with model: [@user, @image],  local: true do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
            <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
  <% end %>
    <div  class='h-screen grid grid-cols-5'>
        <div class='h-full text-xl flex flex-col col-start-2 col-end-5 items-center border-x-2 border-black justify-center '>
            <div class='w-4/6 h-5/6'>
                <div class="w-full my-4">
                    <%= f.label :title %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :title, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :caption %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :caption, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :price %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.number_field :price, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label 'Photo' %><br />
                    <div class='mt-6 border-black'>
                        <%= f.file_field :img, :style => 'width: 100%' %>
                    </div>
                </div>
                
                <div class='flex w-full mt-8 flex justify-around'>
                    <button class='bg-black self-center mt-8 text-white py-2 px-4 '><%= f.submit 'Update'%></button>
                    <button class='bg-grey self-center mt-8 text-black py-2 px-4 '><%= link_to 'Cancel', :back %></button>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Caption</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user_id %></td>
        <td><%= image.title %></td>
        <td><%= image.caption %></td>
        <td><%= image.price %></td>
        <td><%= link_to 'Show', user_image_path(@user, image) %></td>
        <td><%= link_to 'Edit', edit_user_image_path(@user, image) %></td>
        <td><%= link_to 'Destroy', user_image_path(@user, image), method: :delete, data: { confirm: 'Are you sure?' }%></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_user_image_path(@user) %>

app/views/images/insufficient_funds.html.erb
<div class="min-w-screen h-screen animated fadeIn faster  fixed  left-0 top-0 flex justify-center items-center inset-0 z-50 outline-none focus:outline-none" id="modal-id">
   	<div class="absolute bg-black opacity-80 inset-0 z-0"></div>
    <div class="w-full max-w-lg p-5 relative mx-auto my-auto shadow-lg bg-black ">
      <!--content-->
      <div class="">
        <!--body-->
        <div class="text-center p-5 flex-auto justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 -m-1 flex items-center mx-auto" fill="none" viewBox="0 0 24 24" stroke="white">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
          </svg>

          <h2 class="text-xl text-white font-primary py-4 ">Insufficient funds</h3>
        </div>
        <!--footer-->
        <div class="p-3  mt-2 text-center space-x-4 md:block">
            <button class="mb-2 md:mb-0 bg-white px-5 py-2 text-sm shadow-sm font-medium tracking-wider text-black hover:shadow-lg hover:bg-gray-100">
                <%= link_to 'Load my wallet', :controller => 'users', :action => 'edit', :id => current_user.id  %>
            </button>
            <button class="mb-2 md:mb-0 bg-grey px-5 py-2 text-sm shadow-sm font-medium tracking-wider text-black hover:shadow-lg hover:bg-gray-100">
                <%= link_to 'Cancel', :back  %>
            </button>
        </div>
      </div>
    </div>
</div>

app/views/images/new.html.erb
<%= form_with model: [@user, @image],  local: true do |f| %>
    <div  class='h-screen grid grid-cols-5'>
        <div class='h-full text-xl flex flex-col col-start-2 col-end-5 items-center border-x-2 border-black justify-center '>
            <div class='w-4/6 h-5/6'>
                <div class='h-36 w-full bg-black flex flex-col justify-center items-center text-white mb-8'>
                    <%= f.label 'Upload a photo'%>
                    <%= f.file_field :img %>
                </div>
            
                <div class="w-full my-4">
                    <%= f.label :title %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.text_field :title, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full my-4">
                    <%= f.label :caption %><br />
                    <div class='border-b-2 border-black w-full'>
                        <%= f.text_area :caption, :style => 'width: 100%' %>
                    </div>
                </div>
            
                <div class="w-full my-4">
                    <%= f.label :price %><br />
                    <div class='mt-6 border-b-2 border-black'>
                        <%= f.number_field :price, :style => 'width: 100%' %>
                    </div>
                </div>

                <div class="w-full mt-8 flex justify-center">
                    <button class='bg-black text-white py-2 px-4 '><%= f.submit 'Save'%></button>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/images/show.html.erb
<div class='h-screen w-screen flex flex-col justify-center items-center'>
  <div class='mt-10 h-auto w-3/5 flex flex-col justify-center items-center'>
    <button class='text-grey text-xl self-end'>
      <%= link_to(user_path(@user)) do %>
        <i class="fas fa-times"></i>
      <% end %>
    </button>
    <div class='w-full grid grid-cols-2'>
      <% if @image.title != nil %>
        <span class='col-start-1 font-bold text-2xl'><%= @image.title %></span>
      <% end %>
      <% if @image.price != nil and @image.price > 0 %>
        <span class='col-start-2 flex justify-end font-bold text-2xl'>PHP <%= @image.price %></span>
      <% end %>
    </div>
    <% if @image.caption != nil %>
      <span class='h-auto self-start text-base mt-8'><%= @image.caption %></span>
    <% end %>
    <image class='mt-8'><%= image_tag @image.img.to_s, :style => 'object-fit:contain; max-width:800px; max-height:500px'  %></image>
    <div class='btns mt-8 mb-4'>
      <% if @image.user_id == current_user.id %>
        <div class='flex'>
          <span class='mx-2'><%= link_to 'Delete', user_image_path(@user, @image), method: :delete, data: { confirm: 'Are you sure?' } %></span> |
          <span class='mx-2'><%= link_to 'Edit', edit_user_image_path(@user, @image) %></span>
        </div>
      <% else %>
        <% if @image.price != nil and @image.price > 0 %>
          <button class='px-4 py-2 bg-black text-white mt-8'><%= link_to 'BUY', images_buy_path(@image) %></button>
        <% end %>
      <% end %>
    </div>
  </div>
</div>